platform :ios, '7.0'

pod 'AFNetworking'
pod 'MBProgressHUD', '~> 0.5'
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'Bolts'
pod 'ParseCrashReporting'
pod 'iOS-Slide-Menu', '~> 1.5'
pod 'InstagramKit', '~> 3.6'
pod 'InstagramKit/UICKeyChainStore'
pod 'JTImageButton'
pod 'RMStore', '~> 0.7'
pod 'RMStore/NSUserDefaultsPersistence'
pod 'CustomIOSAlertView', '~> 0.9.3'
pod 'TapjoySDK'
pod 'FBSDKShareKit'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'DLRadioButton', '~> 1.4'
pod 'Branch'
pod 'SDWebImage', '~>3.7'