platform :ios, '7.0'

pod 'AFNetworking'
pod 'MBProgressHUD', '~> 0.5'
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'Bolts'
pod 'ParseCrashReporting'
pod 'iOS-Slide-Menu', '~> 1.5'
pod 'InstagramKit', '~> 3.6'
